### ISSUE TITLE
Example of dbxref on EQ/human readable def?

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#20]
@dosumis Would you mind extending this [pattern](https://github.com/FlyBase/drosophila-phenotype-ontology/blob/master/src/patterns/dosdp-patterns/dpoAbnormalEntity.yaml) to allow the generation of 

1. a definition in the usual way and
2. a dbxref (list var) on that definition?

I think on second thought the issues referenced [here](https://github.com/INCATools/dosdp-tools/issues/137#issuecomment-509707880) are not the same after all. The ticket should be sufficiently general: allow committing ALL columns pertaining to any kinds of annotations; But the current attempt to extend the uPheno patterns was actually dbxrefs *on the terms*. If we want dbxrefs on the EQs and the human readable diffs, we need to do some more work to extend the general uPheno scheme. If I get an example from you, I can get the ball rolling! Merci :)

**Comment by dosumis** [comment]
```yaml

vars:
  entity: "'thing'"
  quality: "'thing'"

data_list_vars:
  def_xrefs: "xsd:string"
  cross_references: "xsd:string"
  exact_syn: "xsd:string"
  narrow_syn: "xsd:string"
  broad_syn: "xsd:string"
  related_syn: "xsd:string"
   
def: 
  text: "fu %s bar %s"
  vars:
    - 'regulated_activity'
    - 'regulated_activity' 
  xrefs: 
     value: def_xrefs

xrefs: 
   value: cross_references
exact_synonyms: 
    value: exact_syn
narrow_synonyms: 
    value: narrow_syn
broad_synonyms: 
    value: broad_syn
related_synonyms: 
    value: related_syn
```

**Comment by matentzn** [comment]
Woops yeah, so was the right thing after all. Works. Thanks a lot! :)

So the minmal version seems to be this:

```
data_list_vars:
  def_xrefs: xsd:string

def:
  text: "Abnormality of %s."
  vars:
    - entity
  xrefs: def_xrefs
```

You had this:

```
xrefs: 
   value: cross_references
```

Was there any purpose in that?

**Comment by dosumis** [comment]
```yaml
xrefs: 
   value: cross_references
```

This is for xrefs on the term - not on the definition (note the nesting)

**Comment by matentzn** [comment]
Ah gotcha. Cheers.

[Starting](https://github.com/FlyBase/drosophila-phenotype-ontology/blob/master/src/patterns/dosdp-patterns/dpoAbnormalEntityTestXref.yaml) point for the big pattern extension.

**Comment by dosumis** [comment]
Might be worth just including all (commonly used) OBO annotation fields in all patterns.  Given that this would cause pattern bloat - we should probably invesitgate doing this via a json import statement.

synonyms (various flavours); xrefs; comment; subset*; namespace;  deprecated*, consider/replace? 

* DOSDPs need more work to support this properly.

**Comment by matentzn** [comment]
I while I could use the pattern above to generate, if i run your schema checker it complains:

```
/tools//simple_pattern_tester.py:23: UserWarning: deque(['additionalProperties']) => Additional properties are not allowed ('xrefs' was unexpected) => []
```

**Comment by matentzn** [comment]
And +1 on including them all. I have no problem with bloating! Its yaml so bulk edits should be easy peasy with python.

**Comment by matentzn** [comment]
This caused schema checker fail:

```
pattern_name: dpoAbnormalEntity
pattern_iri: http://purl.obolibrary.org/obo/dpo/patterns/dpoAbnormalEntity.yaml
description: "Any unspecified abnormality of an entity."

classes:
  thing: owl:Thing
  abnormal: PATO:0000460

relations: 
  inheres_in_part_of: RO:0002314
  inheres_in: RO:0000052
  has_modifier: RO:0002573
  has_part: BFO:0000051
  
vars:
  entity: "'thing'"
  quality: "'thing'"

data_list_vars:
  def_xrefs: xsd:string
  cross_references: "xsd:string"
  #exact_syn: "xsd:string"
  #narrow_syn: "xsd:string"
  #broad_syn: "xsd:string"
  #related_syn: "xsd:string"

def:
  text: "Abnormality of %s."
  vars:
    - entity
  xrefs: def_xrefs

name:
  text: "abnormal %s"
  vars:
   - entity

xrefs: 
   value: cross_references

#exact_synonyms: 
#    value: exact_syn
#narrow_synonyms: 
#    value: narrow_syn
#broad_synonyms: 
#    value: broad_syn
#related_synonyms: 
#    value: related_syn

equivalentTo:
  text: "%s and ('inheres_in' some %s) and ('has_modifier' some 'abnormal')"
  vars:
    - quality
    - entity
```
